"""Kiss coverage witnesses for ops/deepswe_run.py."""
from __future__ import annotations

import deepswe_run as _mod

def test_deepswe_run_kiss_coverage_witnesses() -> None:
    _ = (_mod._docker_backstop_timeout_sec, _mod._remaining_sec, _mod._kill_process_group, _mod._run_with_timeout, _mod.default_deepswe_tasks_root, _mod.default_deepswe_results_dir, _mod.resolve_local_task_dir, _mod.read_task_language, _mod.goal_task_ids, _mod.resolve_materialized_workspace,)
    _ = (_mod.audit_task_entry, _mod.list_deepswe_tasks, _mod.list_deepswe_tasks_with_language, _mod._agent_timeout_result, _mod._grade_timeout_result, _mod.parse_task_dir, _mod.validate_verifier_paths, _mod.timestamp_dir, _mod.apply_in_sandbox_runner_env,)
    _ = (_mod.run_cmd, _mod.git_run, _mod.docker_daemon_available, _mod.skip_docker_selftests, _mod.deepswe_test_fast_grade_enabled, _mod._fast_grade_selftest_result, _mod.ephemeral_cache_find_expr, _mod.sandbox_artifact_find_expr, _mod.docker_purge_shell, _mod.purge_root_owned_ephemeral_caches,)
    _ = (_mod.git_clean_would_remove, _mod.docker_purge_git_clean_targets, _mod.git_clean, _mod.materialize_workspace, _mod.repair_workspace_submodules, _mod.reset_workspace, _mod.refuse_agent_verifier_leaks, _mod.canonical_tool, _mod.parse_yaml_scalar, _mod.precommit_hook_entries,)
    _ = (_mod.precommit_config_has_hook_ids, _mod.precommit_agent_check_commands, _mod.next_makefile_recipe, _mod.makefile_gate_targets, _mod.gate_tool_signals, _mod.dedupe_check_lines, _mod.supplement_makefile_signals, _mod.visit_source_files, _mod.existing_malvin_checks_lines, _mod.discover_deepswe_check_lines,)
    _ = (_mod.discover_deepswe_checks, _mod._python_module_name, _mod.scan_class_level_attributes, _mod._hook_class_names, _mod.python_import_roots, _mod._import_class_preflight, _mod.patch_surface_targets, _mod.render_patch_surface_probe, _mod.scan_pytest_monkeypatch_hooks, _mod.malvin_mem_limit_gb,)
    _ = (_mod.ensure_deepswe_malvin_config, _mod.write_task_plan, _mod.write_plan_and_checks, _mod.apply_patch, _mod.harbor_test_patch_path, _mod._join_shell_continuations, _mod._parse_shell_functions, _mod._parse_shell_array, _mod._parse_shell_scalar, _mod._extract_block_body,)
    _ = (_mod._find_base_mode_body, _mod._normalize_runner_command, _mod._expand_function_calls, _mod._commands_from_base_body, _mod.is_runnable_check_line, _mod._embedded_test_sh_from_patch, _mod._embedded_test_py_from_patch, _mod._baseline_from_test_py_wrapper, _mod._expand_ignore_args_command, _mod._expand_shell_array_refs,)
    _ = (_mod._expand_shell_variables, _mod._find_new_mode_body, _mod.harbor_new_mode_check_lines, _mod.harbor_baseline_check_lines, _mod.harbor_patch_check_lines, _mod.scan_test_patch_monkeypatch_hooks, _mod.harbor_new_tests_check_line, _mod.apply_harbor_test_patch, _mod.resolve_docker_image, _mod.local_agent_image_tag,)
    _ = (_mod._toolchain_copy_ignore, _mod._copy_toolchain_tree, _mod.build_local_agent_image, _mod.cursor_env_docker_args, _mod._docker_common_mounts, _mod.write_trial_scripts, _mod.docker_local_agent_cmd, _mod.docker_local_grade_cmd, _mod.docker_local_eval_cmd, _mod._read_docker_grade_result,)
    _ = (_mod._run_local_docker_subprocess, _mod.run_local_eval_in_docker, _mod.grade_workspace_native, _mod.grade_workspace, _mod.malvin_needs_task_plan, _mod.agent_phase_needs_cursor_credentials, _mod.hello_probe_cmd, _mod.runnable_check_command_lines, _mod._pyproject_project_name, _mod.ecosystem_offline_smoke_commands,)
    _ = (_mod._nested_python_package_smoke_module, _mod._harbor_venv_python_c, _mod.write_deepswe_agent_checks, _mod._is_tox_check_line, _mod.init_checks_cmd, _mod._relay_subprocess_stdout, _mod.run_malvin, _mod.find_latest_malvin_log, _mod.write_metadata, _mod.run_modal_solve,)
    _ = (_mod._is_modal_spend_limit_error, _mod._run_solve_local_docker_fallback, _mod._build_run_metadata, _mod._write_host_run_artifacts, _mod._print_evaluation_summary, _mod.evaluation_smoke_allows_reward_zero, _mod._exit_from_evaluation, _mod._run_local_docker_task, _mod.run_task, _mod._task_kernel_options,)
    _ = (_mod._local_solve_options, _mod.cli, _mod.tasks_cmd, _mod.self_test_cmd, _mod.solve, _mod._test_malvin_repo_root, _mod._test_default_deepswe_tasks_root, _mod._test_resolve_local_task_dir, _mod._test_local_agent_image_tag, _mod._test_solve_local_dry_run_passes_reset,)
    _ = (_mod._test_refuse_apply_solution_on_agent_solve, _mod._test_refuse_agent_new_tests_env_on_agent_path, _mod._test_reset_workspace_removes_harbor_secret_files, _mod._test_local_docker_post_grade_resets_host_workspace, _mod._test_docker_local_eval_cmd, _mod._test_solve_dry_run, _mod._patch_modal_cursor_credentials, _mod._test_solve_modal_missing_credentials, _mod._test_solve_modal_dry_run, _mod._test_solve_modal_full_dry_run,)
    _ = (_mod._test_solve_test_flag_modal_dry_run, _mod._test_solve_test_flag_rejects_skip_grade, _mod._test_solve_test_flag_in_help, _mod._test_solve_resets_workspace_for_agent_runs, _mod._test_solve_command_in_help, _mod._test_task_name_shorthand_routes_to_solve, _mod._test_bare_invocation_shows_usage, _mod._test_list_deepswe_tasks, _mod._test_read_task_language, _mod._test_list_deepswe_tasks_with_language,)
    _ = (_mod._test_discover_deepswe_checks_minimal, _mod._test_discover_deepswe_checks_python_repo, _mod._test_discover_deepswe_checks_stestr_repo, _mod._test_discover_deepswe_checks_stestr_drops_stale_pytest, _mod._test_discover_deepswe_checks_precommit, _mod._test_discover_deepswe_checks_precommit_id_only_meta, _mod._test_write_deepswe_agent_checks_bandit_like_id_only, _mod._test_discover_deepswe_checks_tox_lint, _mod._test_discover_deepswe_checks_tox_envlist_offline_flags, _mod._test_discover_deepswe_checks_existing_malvin_checks,)
    _ = (_mod._test_harbor_patch_check_lines, _mod._test_harbor_baseline_adaptix_if_mode, _mod._test_harbor_baseline_mashumaro_test_py_wrapper, _mod._test_harbor_baseline_httpx_streaming_braced_mode, _mod._test_is_runnable_rejects_unexpanded_variables, _mod._test_write_task_plan, _mod._test_write_plan_and_checks_discovers, _mod._test_parse_task_dir_does_not_require_test_sh, _mod._test_validate_verifier_paths_fails_without_test_sh, _mod._test_scan_pytest_monkeypatch_hooks,)
    _ = (_mod._test_scan_class_level_attributes, _mod._test_patch_surface_targets_prefers_config_style_classes, _mod._test_render_patch_surface_probe_roundtrip, _mod._test_write_plan_and_checks_includes_patch_surface_probe, _mod._test_is_modal_spend_limit_error, _mod._test_solve_modal_spend_limit_falls_back_to_local_dry_run, _mod._test_tasks_command, _mod._test_ephemeral_cache_find_expr, _mod._test_repair_workspace_submodules_noop_without_gitmodules, _mod._test_repair_workspace_submodules_after_stale_gitdir,)
    _ = (_mod._test_reset_workspace_removes_user_pycache, _mod._test_purge_root_owned_ephemeral_caches_docker_cmd, _mod._test_git_clean_would_remove_and_docker_purge_targets, _mod._test_purge_root_owned_sandbox_artifacts_docker, _mod._test_scan_class_level_attributes_skips_non_utf8, _mod._test_purge_root_owned_ephemeral_caches_docker, _mod._test_run_malvin_uses_plan_name_not_at_notation, _mod._test_run_malvin_do_uses_prompt_not_plan, _mod._test_init_checks_cmd_uses_fail_fast_source, _mod._test_write_deepswe_agent_checks_preseeds_file,)
    _ = (_mod._test_write_deepswe_agent_checks_ecosystem_fallback, _mod._test_harbor_venv_python_c_prefers_virtual_env, _mod._test_evaluation_smoke_allows_reward_zero, _mod._test_run_malvin_init_checks_preseeds_then_shells, _mod._test_agent_phase_needs_cursor_credentials, _mod._test_resolve_malvin_cmd_prefers_repo_target, _mod._test_apply_in_sandbox_runner_env, _mod._test_run_task_in_sandbox_sets_uv_offline, _mod._test_relay_subprocess_stdout_sets_force_tee_env, _mod._test_solve_path_accepts_hello_command,)
    _ = (_mod._test_local_grade_only_apply_solution, _mod._test_malvin_mem_limit_gb_from_task_memory, _mod._test_ensure_deepswe_malvin_config_seeds_home_config, _mod._test_ensure_deepswe_malvin_config_skips_default_memory, _mod._test_trial_scripts_deny_runtime_installs, _mod._test_host_preseed_init_checks, _mod.build_smoke_grade_script, _mod._test_audit_task_entry_uses_materialized_workspace, _mod._test_audit_task_entry_flags_missing_materialized_workspace, _mod._minimal_timeout_task_tree,)
    _ = (_mod._test_remaining_sec_floors_at_zero, _mod._test_run_with_timeout_kills_slow_command, _mod._test_exit_after_agent_timeout_grade_pass, _mod._test_exit_after_agent_timeout_grade_fail, _mod._test_agent_timeout_skip_grade_exits_zero, _mod._test_verifier_timeout_forces_fail, _mod._test_grade_workspace_native_ambient_env, _mod._test_run_task_agent_phase_respects_deadline, _mod._test_combined_path_agent_timeout_still_grades, _mod._test_finalize_modal_eval_skips_agent_exit_on_timed_out,)
    _ = (_mod._test_run_local_eval_in_docker_passes_backstop_timeout, _mod.run_self_tests, _mod.SubprocessResult, _mod.TaskSpec, _mod.TaskAliasGroup, _mod.TaskAliasGroup.resolve_command,)
    assert True
