"""Kiss coverage witnesses for ops/deepswe_modal.py."""
from __future__ import annotations

import deepswe_modal as _mod
from toolchain_repos import load_ops_entry

def test_deepswe_modal_kiss_coverage_witnesses() -> None:
    _ = (_mod.cursor_api_allowlist_cache_path, _mod.read_cursor_api_allowlist_cache, _mod.write_cursor_api_allowlist_cache, _mod.invalidate_cursor_api_allowlist_cache, _mod.critical_cursor_hosts_failed, _mod.sandbox_app, _mod.malvin_upload_ignore, _mod.workspace_mount_ignore, _mod._upload_ignore_names, _mod._copytree_ignore_factory,)
    _ = (_mod.stage_toolchain_repo, _mod.stage_malvin_repo, _mod.resolve_cursor_api_cidrs_from_hosts, _mod.resolve_cursor_api_cidrs, _mod.cidr_probe_image, _mod.agent_peer_probe_image, _mod._probe_sandbox_timeout, _mod._is_transient_modal_probe_error, _mod._is_modal_spend_limit_error, _mod._allowlist_cache_only_mode,)
    _ = (_mod._use_cached_allowlist_verbatim, _mod._run_modal_cidr_probe_script_once, _mod._run_modal_cidr_probe_script, _mod.resolve_cursor_api_cidrs_in_modal_sandbox, _mod.resolve_cursor_api_cidrs_under_allowlist, _mod.resolve_cursor_api_cidrs_under_allowlist_peers, _mod.validate_cursor_https_under_allowlist, _mod.resolve_cursor_api_cidrs_from_agent_peers, _mod.resolve_agent_session_peers_under_allowlist, _mod._observe_agent_session_under_allowlist,)
    _ = (_mod.parse_agent_peer_probe_payload, _mod.peer_ips_not_covered_by_allowlist, _mod.agent_session_ok_under_allowlist, _mod.union_ipv4_cidrs, _mod.union_optional_probe_cidrs, _mod.compress_ipv4_cidrs, _mod.allowlist_near_modal_cap, _mod.host_cidrs_not_covered_by_allowlist, _mod._run_allowlist_dns_fixpoint, _mod._expand_allowlist_for_https,)
    _ = (_mod.refresh_cached_allowlist, _mod._refresh_cached_allowlist_live, _mod.pin_cursor_api_hosts_in_sandbox, _mod._merge_allowlist_agent_peers, _mod.finalize_allowlist_with_agent_validation, _mod._agent_allowlist_preflight_failed, _mod.resolve_agent_sandbox_cidrs, _mod._build_agent_sandbox_cidrs_cold, _mod.agent_sandbox_network_kwargs, _mod.modal_cidr_allowlist,)
    _ = (_mod.sandbox_network_kwargs, _mod.agent_sandbox_resource_kwargs, _mod.agent_sandbox_timeout_sec, _mod.grade_sandbox_resource_kwargs, _mod.relay_stream, _mod.stream_process_output, _mod._image_build_shell_command, _mod._image_build_shell_commands, _mod._looks_like_image_prep_failure, _mod.format_modal_image_prep_error,)
    _ = (_mod._ops_local_files, _mod._materialize_public_verifier_venv, _mod.harbor_image, _mod.mount_task_tree, _mod.mount_eval_context, _mod.mount_agent_context, _mod.agent_process_tree_cleanup_script, _mod.wrap_agent_exec_argv, _mod.cleanup_agent_process_tree, _mod._safe_harvest_workspace,)
    _ = (_mod.inject_verifier_files, _mod.mount_local_toolchain, _mod.read_remote_file, _mod.read_remote_bytes, _mod.persist_grading_artifacts, _mod._can_overlay_existing_file, _mod._tar_extract_member, _mod._extract_tar_over_workspace, _mod.harvest_sandbox_workspace, _mod.harvest_sandbox_logs,)
    _ = (_mod.parse_deepswe_run_result, _mod._execute_trial_bash_in_sandbox, _mod.run_deepswe_run_in_sandbox, _mod.inject_trial_scripts, _mod.offline_check_tool_install_commands, _mod.offline_agent_checks, _mod.warm_offline_workspace_layer, _mod.warm_precommit_hooks_layer, _mod.harbor_agent_image, _mod.cursor_credentials_available,)
    _ = (_mod.require_cursor_credentials_for_agent, _mod.cursor_secrets, _mod.write_metadata, _mod.load_agent_sandbox_metadata, _mod.finalize_modal_eval, _mod.run_modal_eval, _mod.dispatch_main, load_ops_entry("deepswe_modal").main, load_ops_entry("deepswe_modal").entrypoint, _mod._test_repo_roots, _mod._test_default_deepswe_results_dir,)
    _ = (_mod._test_cursor_cidrs, _mod._test_modal_cidr_allowlist_ipv4_only, _mod._test_network_kwargs, _mod._test_sandbox_resource_kwargs, _mod._test_agent_sandbox_timeout_sec, _mod._test_compress_ipv4_cidrs, _mod._test_allowlist_near_modal_cap, _mod._test_agent_sandbox_cidrs_union, _mod._test_agent_sandbox_cidrs_union_body, _mod._test_critical_cursor_hosts_failed,)
    _ = (_mod._test_cursor_api_allowlist_cache, _mod._test_resolve_agent_sandbox_cidrs_uses_cache, _mod._test_host_cidrs_not_covered_by_allowlist, _mod._test_peer_ips_not_covered_by_allowlist, _mod._test_observe_agent_peers_script_nonblocking, _mod._test_parse_agent_peer_probe_payload, _mod._test_agent_session_ok_under_allowlist, _mod._test_finalize_allowlist_raises_on_stall, _mod._test_resolve_agent_sandbox_cidrs_cold_rebuild_on_preflight_fail, _mod._test_refresh_cached_allowlist_skips_agent_probes,)
    _ = (_mod._test_resolve_agent_sandbox_cidrs_skips_finalize_for_probe, _mod._test_refresh_cached_allowlist_merges_host_dns, _mod._test_refresh_cached_allowlist_runs_post_https_agent_peer, _mod._test_refresh_cached_allowlist_runs_fixpoint_when_host_dns_covered, _mod._test_refresh_cached_allowlist_expands_for_https, _mod._test_expand_allowlist_for_https_merges_extra_ips, _mod._test_run_allowlist_dns_fixpoint_stops_at_fixpoint, _mod._test_pin_cursor_api_hosts_script_pins_all_allowed_ips, _mod._test_pin_cursor_api_hosts_in_sandbox, _mod._test_post_https_agent_peer_merge_always_runs,)
    _ = (_mod._test_agent_sandbox_network_kwargs, _mod._test_hello_sandbox_runs_full_allowlist_probes, _mod._test_stream_helpers, _mod._test_cursor_secrets, _mod._test_require_cursor_credentials_for_agent, _mod._test_run_modal_eval_missing_credentials, _mod._test_persist_grading_artifacts, _mod._test_tier_a_before_workspace_harvest, _mod._test_agent_grade_call_order_cleanup_harvest_inject, _mod._test_cleanup_agent_process_tree_is_pgid_scoped,)
    _ = (_mod._test_cleanup_agent_process_tree_kills_local_orphan_tree, _mod._test_wrap_agent_exec_records_pgid, _mod._test_wrap_agent_exec_runs_and_records_pgid_locally, _mod._test_load_agent_sandbox_metadata, _mod._test_deepswe_exec_binary_stream_kwargs, _mod._test_harvest_binary_model_patch, _mod._test_parse_deepswe_run_result_binary_patch, _mod._test_grade_in_sandbox_network, _mod._test_agent_sandbox_network, _mod._test_agent_sandbox_open_network,)
    _ = (_mod._test_harvest_sandbox_workspace, _mod._test_extract_tar_over_workspace_readonly_target, _mod._test_can_overlay_existing_file_denies_unremovable, _mod._test_extract_tar_over_workspace_skips_unremovable, _mod._test_mount_eval_context_recipe, _mod._test_mount_agent_context_excludes_tests, _mod._test_harbor_agent_image_materializes_public_verifier_venv, _mod._test_no_pytest_disable_in_harbor_agent_image_env, _mod._test_inject_verifier_files, _mod._test_validate_toolchain_repos,)
    _ = (_mod._test_offline_check_tool_install_commands, _mod._test_offline_agent_checks, _mod._test_read_remote_file, _mod._test_read_remote_bytes, _mod._test_write_metadata, _mod._test_finalize_modal_eval_echoes_agent_stdout, _mod._test_resolve_cursor_api_cidrs_mocked, _mod._test_upload_ignore_patterns, _mod._test_stage_malvin_repo, _mod._test_format_modal_image_prep_error,)
    _ = (_mod._test_warm_offline_workspace_layer, _mod._test_warm_precommit_hooks_layer, _mod._test_harbor_agent_image_warms_precommit_hooks, _mod._test_harbor_image_aiomonitor_pydantic_reconcile, _mod._test_harbor_image_registry_skips_bulk_pip_replay, _mod._test_harbor_image_prefers_registry_for_fastapi_task, _mod._test_harbor_image_builds_from_dockerfile_with_cache_bust, _mod._test_harbor_image_pulls_registry_when_no_dockerfile, _mod._test_mount_local_toolchain_recipe, _mod._test_docstring_normative_command,)
    _ = (_mod._test_probe_sandbox_timeout, _mod._test_is_transient_modal_probe_error, _mod._test_is_modal_spend_limit_error, _mod._test_refresh_cached_allowlist_cache_only_mode, _mod._test_refresh_cached_allowlist_spend_limit_falls_back, _mod._test_run_modal_cidr_probe_script_retries_transient_timeout, _mod._test_sandbox_app, _mod._test_self_test_flag, _mod._fake_stage_malvin_repo, _mod._test_run_modal_eval_modal_agent_modal_grade,)
    _ = (_mod.run_cidr_allowlist_unit_tests, _mod.run_allowlist_refresh_unit_tests, _mod.run_agent_toolchain_unit_tests, _mod.run_harvest_sandbox_unit_tests, _mod.run_harbor_modal_probe_unit_tests, _mod.run_modal_lifecycle_eval_unit_tests, _mod.run_unit_tests, _mod._RecordingImage, _mod._RecordingImage.__init__, _mod._RecordingImage.add_local_dir,)
    _ = (_mod._RecordingImage.add_local_file, _mod._RecordingImage.run_commands, _mod._RecordingImage.env,)
    assert True
