#[test]
fn kiss_probe_static_tokens_a() {
    fake_events_for_prompt("", "", "");
    empty_agent_end();
    streamed_hello_events();
    map_agent_end();
    last_assistant_text();
    text_from_blocks();
    aggregate_usage();
    create_tool_registry();
    from_builtin();
    run_isolated_bash();
    description();
    parameters();
    effects();
    execute();
    drain_agent_events();
    recv_event_with_idle();
}

#[test]
fn kiss_probe_static_tokens_b() {
    handle_mapped_events();
    finish_after_channel_closed();
    finish_run_done();
    send_fake_prompt();
    is_providers_noise_line();
    col();
    tool_call();
    deref();
    deref_mut();
    last_text();
    run_models_pi_only_with_openrouter_key();
    assert_live_auth_filter();
    is_provider_listable();
    models_json_provider();
    leftover_pi_runtime_threads();
    start_embedded_mem_watch();
    watch_embedded_memory();
    session_spawn_tests::fake_session_begin_end_leaves_no_pi_runtime_thread();
}

#[test]
fn kiss_probe_static_models_refresh_tokens() {
    ProviderModelCache();
    cache_fetched_at_is_fresh();
    unix_now_secs();
    load_provider_cache();
    save_provider_cache();
    refresh_pi_provider_caches_if_stale();
    merge_registry_with_live();
    append_live_models();
    append_static_models_without_live();
    static_registry_lookup();
    provider_needs_refresh();
    fetch_provider_models_sync();
    resolve_provider_api_key();
    authenticated_providers();
    is_provider_listable();
    models_json_provider();
    provider_supports_pi_live_model_fetch();
    openai_compat_models_url();
    PI_MODEL_CACHE_TTL();
}

#[test]
fn kiss_probe_static_local_endpoint_tokens() {
    parse_http_authority_host_port();
    http_base_url_is_listening();
    keyless_local_provider_is_listening();
    KEYLESS_LOCAL_REACHABILITY_TIMEOUT();
    scheme_and_rest();
    default_port_for_scheme();
    parse_bracketed_host_port();
    parse_host_port_pair();
    ensure_local_llm();
    housekeep_local_llms();
    model_needs_local_llm();
    run_local_llm_manager();
    reclaim_stale_manager_files();
    ensure_via_manager();
    hold_via_manager();
    release_via_manager();
    touch_via_manager();
    start_keepalive();
    stop_keepalive();
    hold_local_llm();
    release_local_llm();
    INTERNAL_MANAGER_FLAG();
    DEFAULT_IDLE_SECS();
    ManagerRequest();
    ManagerResponse();
    ensure_provider_running();
    try_acquire_lock();
    idle_secs();
    manager_sock_path();
    manager_lock_path();
    ollama_bin();
    KEYLESS_LOCAL_REACHABILITY_TIMEOUT();
    scheme_and_rest();
    default_port_for_scheme();
    parse_bracketed_host_port();
    parse_host_port_pair();
}

#[test]
fn kiss_probe_static_openrouter_pricing_tokens() {
    warm_openrouter_pricing_cache();
    lookup_model_cost();
    fetch_billed_cost_from_generation_ids();
    GenerationResponse();
    GenerationData();
    aggregate_cost_usd();
    AggregatedCostUsd();
    OpenRouterModelsResponse();
    OpenRouterModelEntry();
    OpenRouterPricing();
    PricingCache();
    parse_rate_per_million();
    model_cost_from_pricing();
    load_cache();
    save_cache();
    fetch_live_pricing_sync();
    fetch_live_pricing_async();
    pricing_from_models_body();
    openrouter_lookup_ids();
    models_url();
}
